"* ************************************************************************** *"
"*                                                                            *"
"*                                                        :::      ::::::::   *"
"*   .vimrc                                             :+:      :+:    :+:   *"
"*                                                    +:+ +:+         +:+     *"
"*   By: sbelondr <sbelondr@student.42.fr>          +#+  +:+       +#+        *"
"*                                                +#+#+#+#+#+   +#+           *"
"*   Created: 2020-03-26 18:43:19 by sbelondr          #+#    #+#             *"
"*   Updated: 2020-03-26 18:43:19 by sbelondr         ###   ########.fr       *"
"*                                                                            *"
"* ************************************************************************** *"

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""""" initialize """"""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

execute pathogen#infect()

syntax	on
set		mouse-=a
set		nu
set		ruler
set		colorcolumn=80

"	tab settings
set		tabstop=4
set		shiftwidth=4
set		softtabstop=4
set		noexpandtab
set		autoindent
set		smartindent
set		cindent

set 	encoding=utf-8
set 	modelines=1

set		nocompatible


"	Search ctags for c file
filetype on
filetype detect

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""" function """""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

function InitializeC()
	let		current_folder = getcwd()
	silent exec "!ctags --recurse=yes --exclude=.git --exclude=.svn " . current_folder
	"silent exec \"!ctags -R \" . current_folder

	let g:syntastic_c_include_dirs = ['libft/includes', 'includes']
	let g:syntastic_c_compiler_options = "-Wall -Wextra -Werror"
	let g:syntastic_c_check_header = 1
	let g:syntastic_c_remove_include_errors = 1
	let g:syntastic_always_populate_loc_list = 1
	let g:syntastic_auto_loc_list = 1
	let g:syntastic_check_on_open = 1
	let g:syntastic_check_on_wq = 0
	let g:syntastic_error_symbol = "✗"
endfunction

function GetNormi()
	let file_name=expand('%:p')
	return system("norminette " . file_name)
endfunction

"	Norminette
function Normi()
	set statusline=
	echo GetNormi()
endfunction

"	Norminette
function GetNormiBeta()
	let file_name=expand('%:p')
	return system("python3 /usr/share/norminette-beta/norminette/__main__.py " . file_name)
endfunction

function NormiBeta()
	set statusline=
	echo GetNormiBeta()
endfunction

function NewTab()
	:tabnew
	:Explore
endfunction

function FtPython()
	"	Comment line
	map cl 0i#<Esc>
	map ucl 01x
endfunction

function FtC()
	"	Comment line
	map cl 0i//<Esc>
	map ucl 02x
endfunction

function FtAsm()
	"	Comment line
	map cl 0i;<Esc>
	map ucl 01x
endfunction

function FtGolang()
	" build
	noremap <F7> :GoBuild<CR>
	" doc shift-f7
	noremap <F19> :GoDoc<CR>
	" run
	noremap <F8> :GoRun<CR>
	" shift-F8
	noremap <F20> :GoTest<CR>
	" shift f1
	noremap <F13> :GoDef<CR>
	" ctrl f1
	noremap <F25> :GoImport<CR>
	" alt f1
	noremap <F49> :GoLint<CR>
	" ctrl-F8
	noremap <F32> :TagbarToggle<CR>
	"noremap <F32> :TagbarToggle<CR>
	let g:tagbar_autoclose = 1
	"let g:tagbar_autofocus = 1
	let g:tagbar_show_data_type = 1
	"let g:tagbar_show_tag_linenumbers = 1
	"let g:tagbar_autopreview = 1
	let g:tagbar_wrap = 2
	"let g:tagbar_compact = 1

	let g:tagbar_type_go = {
		\ 'ctagstype' : 'go',
		\ 'kinds'     : [
			\ 'p:package',
			\ 'i:imports:1',
			\ 'c:constants',
			\ 'v:variables',
			\ 't:types',
			\ 'n:interfaces',
			\ 'w:fields',
			\ 'e:embedded',
			\ 'm:methods',
			\ 'r:constructor',
			\ 'f:functions'
		\ ],
		\ 'sro' : '.',
		\ 'kind2scope' : {
			\ 't' : 'ctype',
			\ 'n' : 'ntype'
		\ },
		\ 'scope2kind' : {
			\ 'ctype' : 't',
			\ 'ntype' : 'n'
		\ },
		\ 'ctagsbin'  : 'gotags',
		\ 'ctagsargs' : '-sort -silent'
	\ }

	autocmd VimEnter * nested :TagbarToggle
	:autocmd BufWritePost * :TagbarForceUpdate
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""" initialize theme """""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

if &ft == "c" || &ft == "cpp"
	:call InitializeC()
endif

"	apply theme gruvbox
filetype plugin indent on
let	g:airline_theme='gruvbox'
let	g:gruvbox_color_column='bg1'
let	g:gruvbox_vert_split='gray'
colorscheme	gruvbox
set termguicolors
set background=dark
let g:gruvbox_termcolors=16
let g:gruvbox_contrast_dark='medium'
"let g:gruvbox_transparent_bg = 1
"autocmd VimEnter * hi Normal ctermbg=NONE guibg=NONE

"	format date/time
let	g:airline#extensions#clock#format = '%d/%m %H:%M'
let g:airline#extensions#clock#updatetime = 1000

" option search
set ignorecase
set smartcase
set	incsearch
set	showmatch
set	hlsearch
hi	Search ctermbg=White
hi	Search ctermfg=Blue

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" For mac
let s:clang_library_path='/Library/Developer/CommandLineTools/usr/lib'
if isdirectory(s:clang_library_path)
	let g:clang_library_path=s:clang_library_path
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
""""""""""""""""""""""""""""""""" key binding """""""""""""""""""""""""""""""""
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" resize window
nnoremap <F2> :vertical resize -1<CR>
nnoremap <F3> :vertical resize +1<CR>
nnoremap <F4> :resize +1<CR>
nnoremap <F5> :resize -1<CR>


"	Nerdtree
noremap <F12> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

"	see invisible characters Shift-F5
set		listchars=eol:$,tab:→\ ,trail:.,space:·,extends:>,precedes:<,nbsp:_
noremap <F17> :set list!<CR>
inoremap <F17> <C-o>:set list!<CR>
cnoremap <F17> <C-c>:set list!<CR>

nnoremap <F6> :set relativenumber<CR>
" shift F6
nnoremap <F18> :set norelativenumber<CR>

" call norminette
noremap <F7> :call Normi()<CR>

" call norminette beta
noremap <S-F7> :call NormiBeta()<CR>

noremap <S-F8> :%!xxd<CR>


nnoremap <F9> :call NewTab()<CR>
" shift F9
nnoremap <F21> :tabnew<CR>
nnoremap <F10> gt<CR>
" shift f10
nnoremap <F22> gT<CR>

"	Comment line
"map cl 0i//<Esc>
"map ucl 02x


let hash = ['python', 'bash', 'sh']
let dblcomment = ['c', 'cpp']
let semicolon = ['asm', 's']
let quote = ['vim']
let golang = ['go']

if index(dblcomment, &filetype) != -1
	:call FtC()
elseif index(hash, &filetype) != -1
	:call FtPython()
elseif index(semicolon, &filetype) != -1
	:call FtAsm()
elseif index(golang, &filetype) != -1
	:call FtGolang()
endif

" edit indent for yaml file
autocmd FileType yaml setlocal ai ts=2 sw=2 et
